---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: moonitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: prometheus
data:
  prometheus.yaml: |-
    envplaceholder
